# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     app.security.login_form_authenticator:
         class: AppBundle\Security\LoginFormAuthenticator
         autowire: true
     app.doctrine.hash_password_listener:
         class: AppBundle\Doctrine\HashPasswordListener
         autowire: true
         tags:
             - {name: doctrine.event_subscriber}
     app.car_voter:
         class: AppBundle\Security\CarVoter
         tags:
             - {name: security.voter}
     app.user_voter:
         class: AppBundle\Security\UserVoter
         tags:
             - {name: security.voter}
     app.techs_voter:
         class: AppBundle\Security\TechSheetVoter
         tags:
             - {name: security.voter}
     app.ticket_voter:
         class: AppBundle\Security\TicketVoter
         tags:
             - {name: security.voter}