<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Voiture extends \AppBundle\Entity\Voiture implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'Disponibilite', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'photos', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'dateAjout', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'nomVoiture', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'ModeleVoiture', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'ficheTech', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'Utilisateur', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'Constructeur', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'argus'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'Disponibilite', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'photos', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'dateAjout', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'nomVoiture', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'ModeleVoiture', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'ficheTech', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'Utilisateur', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'Constructeur', '' . "\0" . 'AppBundle\\Entity\\Voiture' . "\0" . 'argus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Voiture $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArgus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArgus', []);

        return parent::getArgus();
    }

    /**
     * {@inheritDoc}
     */
    public function setArgus($argus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArgus', [$argus]);

        return parent::setArgus($argus);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomVoiture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomVoiture', []);

        return parent::getNomVoiture();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomVoiture($nomVoiture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomVoiture', [$nomVoiture]);

        return parent::setNomVoiture($nomVoiture);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructeur', []);

        return parent::getConstructeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstructeur($Constructeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstructeur', [$Constructeur]);

        return parent::setConstructeur($Constructeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getModeleVoiture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeleVoiture', []);

        return parent::getModeleVoiture();
    }

    /**
     * {@inheritDoc}
     */
    public function setModeleVoiture($ModeleVoiture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeleVoiture', [$ModeleVoiture]);

        return parent::setModeleVoiture($ModeleVoiture);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', []);

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur($Utilisateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', [$Utilisateur]);

        return parent::setUtilisateur($Utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getFicheTech()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFicheTech', []);

        return parent::getFicheTech();
    }

    /**
     * {@inheritDoc}
     */
    public function setFicheTech(\AppBundle\Entity\FicheTech $ficheTech)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFicheTech', [$ficheTech]);

        return parent::setFicheTech($ficheTech);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibilite', []);

        return parent::getDisponibilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponibilite($Disponibilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponibilite', [$Disponibilite]);

        return parent::setDisponibilite($Disponibilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotos', []);

        return parent::getPhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotos($photos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotos', [$photos]);

        return parent::setPhotos($photos);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjout', []);

        return parent::getDateAjout();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjout($dateAjout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjout', [$dateAjout]);

        return parent::setDateAjout($dateAjout);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
