<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \AppBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'mail', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'numTel', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'dateNaissance', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'adresse', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'codePostal', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'ville', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'pays', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'divulgation', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'ipCourante', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'historique', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'Username', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'Password', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'plainpassword', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'Voitures', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'roles', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'ficheTech', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'token'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'mail', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'numTel', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'dateNaissance', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'adresse', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'codePostal', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'ville', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'pays', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'divulgation', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'ipCourante', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'historique', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'Username', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'Password', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'plainpassword', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'Voitures', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'roles', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'ficheTech', '' . "\0" . 'AppBundle\\Entity\\Utilisateur' . "\0" . 'token'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getFicheTech()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFicheTech', []);

        return parent::getFicheTech();
    }

    /**
     * {@inheritDoc}
     */
    public function setFicheTech($ficheTech)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFicheTech', [$ficheTech]);

        return parent::setFicheTech($ficheTech);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoitures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoitures', []);

        return parent::getVoitures();
    }

    /**
     * {@inheritDoc}
     */
    public function setVoitures($Voitures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVoitures', [$Voitures]);

        return parent::setVoitures($Voitures);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($Username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$Username]);

        return parent::setUsername($Username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($Password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$Password]);

        return parent::setPassword($Password);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTel', []);

        return parent::getNumTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTel($numTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTel', [$numTel]);

        return parent::setNumTel($numTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$codePostal]);

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays($pays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getDivulgation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDivulgation', []);

        return parent::getDivulgation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDivulgation($divulgation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDivulgation', [$divulgation]);

        return parent::setDivulgation($divulgation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpCourante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpCourante', []);

        return parent::getIpCourante();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpCourante($ipCourante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpCourante', [$ipCourante]);

        return parent::setIpCourante($ipCourante);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistorique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistorique', []);

        return parent::getHistorique();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistorique($historique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistorique', [$historique]);

        return parent::setHistorique($historique);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainpassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainpassword', []);

        return parent::getPlainpassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainpassword($plainpassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainpassword', [$plainpassword]);

        return parent::setPlainpassword($plainpassword);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

}
